port 26379
dir /tmp
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor fstec-master redis-master 6379 1
sentinel down-after-milliseconds fstec-master 5000
sentinel failover-timeout fstec-master 10000
sentinel parallel-syncs fstec-master 1
